apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lab
  labels:
    app: myapp
    version: 1.23.4
  name: myapp-1.23.4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: 1.23.4
  strategy: {}
  template:
    metadata:
      labels:
        app: myapp
        version: 1.23.4
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: v1-page
          mountPath: /usr/share/nginx/html/ 
      volumes:
      - name: v1-page
        configMap:
          name: myapp-v1-page
          items:
          - key: content 
            path: index.html
