apiVersion: v1
kind: Service
metadata:
  namespace: lab
  labels:
    app: myapp
  name: myapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
    version: 1.23.4
  type: NodePort